# This makefile aims at procesing all file
# First, TestDict is dictionary that should be generated by root cling.
# Then, all .o file must be generated in order to reduce compile time
# .so library is final aim if no specific excutable file is needed.

# SOURCE = BoardBuffer.cpp BoardsManager.cpp CombineData.cpp Configure.cpp OneGroup.cpp Loop.cpp TPrimaryData.cpp TCombinedData.cpp FileManager.cpp TDetectorInfo.cpp mppc.cpp

PWD = `pwd`

DIR_INC = ./include
DIR_SRC = ./src
DIR_OBJ = ./obj
DIR_BIN = ./bin
DIR_LIB = ./lib

# Search all .cpp files in this directory(main.cpp) and src directory
SRC = $(wildcard ${DIR_SRC}/*.cpp)
# Search all .h files in include directroy
HEADERPRE = $(wildcard ${DIR_INC}/*.h)
HEADER = ${subst ${DIR_INC}/LinkDef.h, ,$(HEADERPRE)}
# substitute all .cpp in $(SRC) with .o, and add related directory path
OBJ = $(patsubst %.cpp,${DIR_OBJ}/%.o,$(notdir ${SRC}) )


# OBJ = BoardBuffer.o BoardsManager.o CombineData.o Configure.o OneGroup.o Loop.o TPrimaryData.o TCombinedData.o FileManager.o TDetectorInfo.o mppc.o GetPosition.o
# HEADER = BoardBuffer.h BoardsManager.h CombineData.h Configure.h OneGroup.h Loop.h TPrimaryData.h TCombinedData.h FileManager.h TDetectorInfo.h mppc.h GetPosition.h



CXXFLAGS = -g -Wall -I${DIR_INC} -I. `root-config --cflags`


LIB = ReadFile
LIBFULL = $(patsubst %,${DIR_LIB}/lib%.so,$(LIB))

DIR_LINK = ./lkdef
LINKDEF = ${DIR_INC}/LinkDef.h
DICTCXX = ${DIR_LINK}/$(LIB)Dict.cxx


# Define uninstall path
UNINSTALLHEADER = $(patsubst %.h,${HOME}/include/%.h,$(notdir ${HEADER}))
UNINSTALLLIB = $(patsubst %.so,${HOME}/lib/%.so,$(notdir ${LIBFULL}))



Excutable = test read treetest treeread ProcessOrigin ReadData DrawSignal GetResult ReadOrigin TestThreshold


$(LIBFULL): $(OBJ) $(DICTCXX)
	@echo Generating lib: $@
	@`root-config --cxx`	-fPIC	-shared	-o	$@	$(OBJ)	$(DICTCXX)	`root-config --libs`  $(CXXFLAGS) -lSpectrum

${DIR_OBJ}/%.o: ${DIR_SRC}/%.cpp ${DIR_INC}/%.h
	@echo Generating: $@
	@`root-config --cxx `	-o	$@	-c	$<	-fPIC $(CXXFLAGS)

$(DICTCXX): $(HEADER)   $(LINKDEF)
	@echo rootcling generating $@
	-@mkdir $(DIR_LINK)
	@rootcling	-f	$@	-c	$(HEADER)
	@cp $(DIR_LINK)/*pcm $(PWD)



clean:
	-rm obj/*.o lib/*.so lkdef/* bin/*
distclean:
	-rm obj/*.o lib/*.so lkdef/* bin/*
	-rm *.root *.pdf $(Excutable) *Dict* filelist


test:  test.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB)	`root-config --libs` $(CXXFLAGS)
	
testRead:  testRead.cpp $(LIBFULL)
	@echo Generating $@
	@`root-config --cxx `	-o	$@	$<	-Llib	-l$(LIB)	`root-config --libs` $(CXXFLAGS)



all: $(Excutable)

install: $(LIBFULL)
	@echo Copying lib and headers to user directory
	-@cp $(LIBFULL) ~/lib
	-@cp $(HEADER) ~/include

uninstall:
	@echo Uninstalling from ${HOME}/lib and ${HOME}/include
	-@rm ${UNINSTALLHEADER}
	-@rm ${UNINSTALLLIB}